import { Geist, Geist_Mono } from "next/font/google";
import AdminSidebar from "../component/AdminSidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <div>
      <AdminSidebar />
      <div className="ml-64">
        {children}
      </div>
    </div>

  );
}
